/******************************************************
* #### jQuery manga reader (mangaeden) v01 ####
* Coded by Ican Bachors 2014.
* http://ibacor.com/labs/jquery-manga-reader-mangaeden/
* Updates will be posted to this site.
******************************************************/

// Example setting URL mangaedenAPI.php
var pehape = 'http://yourdomain.com/plugin/mangaedenAPI.php';
	
eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('q($(V).1n()>=1o){$(V).1p(2(){q($(8).1q()>0){$(\'.g\').r(\'s\',\'W\');$(\'.C\').r(\'s\',\'W\')}1r{$(\'.g\').r(\'s\',\'X\');$(\'.C\').r(\'s\',\'X\')}})}g(1s,0);2 g(d,e){$.D({E:d+\'?F=1t/0/?p=\'+e,G:H,I:\'J\'}).K(2(b){9 c=\'\',u=1u(b[0].u/1v);c+=\'<5 6="j-7-Y">\';c+=\'<4 f="L:1w">1x \'+e+\'/\'+u+\'</4>\';c+=\'<4 f="L:M">1y <Z>\';1z(9 i=0;i<=u;i++){c+=\'<10 N="\'+i+\'" 6="11">\'+i+\'</10>\'}c+=\'</Z></4>\';c+=\'</5>\';c+=\'<5 6="j-7-1A">\';$.k(b[0].7,2(i,a){c+=\'<5 6="v" w-12="\'+b[0].7[i].i+\'">\'+b[0].7[i].t+\'<1B><4 6="j-7-1C">\'+b[0].7[i].h+\' 1D</4></5>\'});c+=\'</5><5 f="13-M:O"><4 f="L:M;"><a 1E="14://j.P/1F/" 1G="1H" f="1I:#1J" Q="?">?</a></4></5>\';$(\'.g\').R(c);$(\'.11\').l(2(){9 a=$(8).1K();g(d,a);m n});$(".v").k(2(){$(8).l(2(){9 a=$(8).15("w-12");$(\'5\').1L(\'v-16\');$(8).1M(\'v-16\');S(d,a);m n})})})}2 S(d,e){$.D({E:d+\'?F=7/\'+e+\'/\',G:H,I:\'J\'}).K(2(b){9 c=\'\';c+=\'<5 f="1N:#1O;13:O;"><17><18>\'+b[0].Q+\'</18></17><1P><x>1Q: </x>\';$.k(b[0].19,2(i,a){c+=\'<4 6="1R">\'+b[0].19[i]+\'</4>\'});c+=\'<5 f="1S-Y:O;"><x>1T: </x>\'+b[0].1U+\'</5>\';c+=\'<1a><y><z>1b</z><z>1V</z></y>\';$.k(b[0].A,2(i,a){c+=\'<y><B><1c 6="1d T 1W" w-1e="\'+b[0].A[i][3]+\'">1b \'+b[0].A[i][0]+\'</1c></B><B>\'+b[0].A[i][1]+\'</B></y>\'});c+=\'</1a></5>\';$(\'.S\').R(c);$(".1d").k(2(){$(8).l(2(){9 a=$(8).15("w-1e");o(d,a,0);m n})})})}2 o(c,d,e){$.D({E:c+\'?F=1X/\'+d+\'/\',G:H,I:\'J\'}).K(2(a){9 b=\'\',U=a[0].1f.1Y;b+=\'<5 6="C">\';b+=\'<4 6="1g"><1h 1i="1j" 6="T 1k" N="<<"></4> \';b+=\'<4>\'+e+\'/\'+(U-1)+\'</4> \';b+=\'<4 6="1l"><1h 1i="1j" 6="T 1k" N=">>"></4>\';b+=\'</5>\';b+=\'<1Z 20="14://21.1m.P/22/\'+a[0].1f[e][1]+\'" 23="" Q="24 25 1m 26 27 j.P">\';$(\'.o\').R(b);q(e<U){$(\'.1l\').l(2(){o(c,d,e+1);m n})}q(e>0){$(\'.1g\').l(2(){o(c,d,e-1);m n})}})}',62,132,'||function||span|div|class|manga|this|var||||||style|ibacor_manga_list|||ibacor|each|click|return|false|ibacor_manga_det||if|css|position||total|bcr_manga_inpo|data|strong|tr|th|chapters|td|ibacor_capter|ajax|url|sub|crossDomain|true|dataType|json|done|float|right|value|20px|com|title|html|ibacor_manga_inpo|btn|leng|window|fixed|static|top|select|option|bachorscp|vvv|padding|http|attr|active|center|h1|categories|table|Chapter|button|bcr_manga_det|ccc|images|bcr_capter_back|input|type|submit|ibacor_tombol|bcr_capter_next|mangaeden|width|768|scroll|scrollTop|else|pehape|list|parseInt|500|left|List|Jump|for|bottom|br|vw|Views|href|labs|target|_BLANK|color|444|val|removeClass|addClass|background|fff|hr|Category|ibacor_kategori|margin|Description|description|Uploaded|ibacor_chapter|chapter|length|img|src|cdn|mangasimg|alt|jquery|plugin|api|by'.split('|'),0,{}))
